Support functions, but without return statements
arsalanc-v2/js-slang pull request #3
Opened 2020-03-22 06:35 UTC by anubh-v

With this PR:
- We can declare functions, but only cannot have return statements in the body
- We can apply functions that we've declared OR the apply the built in functions

Try in the REPL:
`list(amb(1,2,3));`

2020-03-24 15:15 UTC, arsalan0c requested changes
It would be good to add tests for sub-functions as well as functions with `amb` arguments to ensure the Cartesian product gives the expected behaviour

(Tests added in #11)

2020-03-24 15:15 UTC, arsalan0c commented on src/__tests__/non-det-interpreter.ts
> +    `function increment(x) {
This test fails. It seems it is because `map` uses the `return` statement.

2020-03-25 01:46 UTC, anubh-v commented on src/__tests__/non-det-interpreter.ts
> +    `function increment(x) {
Yea, I realised that `map` is a prelude function (written in Source) while others like `pair` / `head` are "builtins" (written in Typescript).

2020-03-25 01:47 UTC, anubh-v commented
I've added a very basic *draft* of the return statements' support (without tail call optimisation)

2020-03-27 09:54 UTC, arsalan0c approved these changes

2020-03-27 16:48 UTC, merged